# Install the pre-commit hooks below with
# 'pre-commit install'

# Auto-update the version of the hooks with
# 'pre-commit autoupdate'

# Run the hooks on all files with
# 'pre-commit run --all'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: poetry run isort 2017 2018 2019 2020 2021 noxfile.py
        language: system
        types: [python]
    -   id: black
        name: black
        entry: poetry run black --target-version=py310 2017 2018 2019 2020 2021 noxfile.py
        language: system
        types: [python]
    -   id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
    -   id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]
