name: CI

on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: jpetrucciani/mypy-check@master
        with:
          path: 2020 
  black:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: jpetrucciani/black-check@master
        with:
          path: 20[19|20] 